name: Jcal
description: 'Download/install the latest version of jcal'
author: Davoud Arsalani <ielts@davoudarsalani.ir>

inputs:
  source:
    required: false
    default: 'docker'
  set_timezone:
    required: false
    default: true
  timezone:
    required: false
    default: 'Asia/Tehran'

runs:
  using: 'composite'
  steps:
    - name: Setting Timezone
      if: ${{ inputs.set_timezone == 'true' }}
      shell: bash
      run: |
        sudo ln -fs /usr/share/zoneinfo/${{ inputs.timezone }} /etc/localtime
        sudo hwclock --systohc --utc
        sudo timedatectl set-ntp true

    - name: Pulling/cloning/downloading
      shell: bash
      run: |
        case '${{ inputs.source }}' in
          clone*|askapache|gnu )
            wget -q 'https://raw.githubusercontent.com/davoudarsalani/scripts/master/install-jcal'
            chmod +x ./install-jcal
            ./install-jcal '${{ inputs.source }}'
          ;;
          docker )
            docker pull davoudarsalani/jcal:jdatetime-alpine-3.15.0
          ;;
        esac

branding:
  icon: calendar
  color: blue
