name: Jcal
description: 'Download/install the latest version of jcal'
author: Davoud Arsalani <ielts@davoudarsalani.ir>

inputs:
  source:
    required: false
    default: 'clone-github'
  set_timezone:
    required: false
    default: true
  timezone:
    required: false
    default: 'Asia/Tehran'

runs:
  using: 'composite'
  steps:
    - name: Setting Timezone
      if: ${{ inputs.set_timezone == 'true' }}
      shell: bash
      run: |
        sudo ln -fs /usr/share/zoneinfo/${{ inputs.timezone }} /etc/localtime
        sudo hwclock --systohc --utc
        sudo timedatectl set-ntp true

    - name: Checking for dependencies
      shell: bash
      run: |
        wget -q 'https://raw.githubusercontent.com/davoudarsalani/scripts/master/install-jcal'
        chmod +x ./install-jcal
        ./install-jcal '${{ inputs.source }}'

branding:
  icon: calendar
  color: blue
